### PR TITLE
Switch to using Option instead of Vec for winner in Context

### PR DESCRIPTION
**Pull request by kyrias**
Tera serializes the Context using serde_json.  Options are serialized as
either the value or null with serde_json.

Signed-off-by: Johannes Löthberg <johannes@kyriasis.com>

### CODE REVIEW

**Comment by jonhoo** [comment]
From memory, the reason I did this was that `if winner` would always register as truthy, even if it was `None`, but maybe that has changed? Or maybe I'm just misremembering?

**Comment by kyrias** [comment]
I'm afraid you appear to be misremembering.  In the stream you weren't able to figure out how to get the value out of an `Option`, because you didn't realize that Tera just serializes the context to a JSON value rather than doing something clever on its own.  (Tera's documentation is *really* lacking in this regard.)  And `serde_json` serializes `Option`s by just either having the value, or `null`.

Your first attempted work around was to iterate over the `Option`, but this of course didn't work since the serialized JSON isn't a list, it's just a plain value.  As a work-around you just made it always be a `Vec` instead.

All in all, `Options` work perfectly well with `if` in tera templates.

**Comment by kyrias** [comment]
([Here](https://youtu.be/8LSNN-Y9Ftg?t=5840) is where you start implementing that part.  The funny thing is that you actually started guessing the proper syntax, but then before actually trying it out you looked at the docs and got confused, and then you never actually tried if that works.)

**Comment by jonhoo** [comment]
Excellent, thanks!

**Pull request merged**
