### PR TITLE
Add CI pipeline

### PR DESCRIPTION
**Pull request by ddugovic**

### CODE REVIEW

**Comment by jonhoo** [comment]
Ah, nice, thank you!

**Comment by ddugovic** [comment]
Thank you for making this useful open source project!

**Comment by jonhoo** [comment]
Out of curiosity, what are you using it for?

**Comment by ddugovic** [comment]
Nothing yet, although I'm considering extending it to become a song request bot (there are many online musicians who struggle with prioritizing requests and adding new songs & PDF URLs to their searchable repertoires).

I do see your caution notice about not using it for anything serious (since votes are not authorized in the current version).

**Pull request merged**
